### ISSUE TITLE
Sentence for css code

### ISSUE THREAD

**Issue by AlexanderPilipenko** [backflip/gulp-iconfont-css#56]
Hi, I suggest changing the style templates, this will simplify the entries in the classes
in these templates: `_icons.css, _icons.less, _icons.scss, _icons.styl`
In the template, this entry:
`.icon:before {...}`
it is better to write like this
`[class^="icon-"], [class*=" icon-"], [data-icon]:before {...}`
`[data-icon]:before {
    content: attr(data-icon) !important;
}`
instead of such a record `<i class="icon icon-name"></i>` it suffices to write so `<i class="icon-name"></i>` and as the data attribute `<i data-icon="&#xe001"></i>`.

**Comment by backflip** [comment]
@AlexanderPilipenko, thanks for your input! However, this very much depends on the CSS "architecture" you are relying on. Since approaches like BEM are very widespread and would roughly correspond to what we are doing here, I think we can keep the template as it is. You can always overwrite it anyway.
